### ISSUE TITLE
Please release the pre-trained mods, thanks!

### ISSUE THREAD

**Issue by skeletonNN** [Diananini/LD-ConGR-CVPR2022#1]

**Comment by Diananini** [comment]
Models download link: https://pan.baidu.com/s/1wE7Ul5qgVpi6ROl_sQfLHA?pwd=x5ia

**Comment by skeletonNN** [comment]
Thanks, but it seems that the authors do not disclose the pre-training model including no gesture here, please do.

**Comment by Diananini** [comment]
The models were uploaded.
