### ISSUE TITLE
Could we train this network just using depth data?

### ISSUE THREAD

**Issue by erwangccc** [Diananini/LD-ConGR-CVPR2022#2]
Thanks for your great work. as the title saying, could we train this network just using depth data?
Have you tried this way?

Thanks!

**Comment by Diananini** [comment]
We tried training the model on depth data. Limited by the long-distance acquisition quality of the depth camera, the recognition performance of using only the depth information is not good

**Comment by erwangccc** [comment]
Thanks for your reply!
