### ISSUE TITLE
Pre-process videos to frames

### ISSUE THREAD

**Issue by erwangccc** [Diananini/LD-ConGR-CVPR2022#5]
@Diananini Hi, sorry to bother you.

You said _"All you need to do is extract frames of the with ffmpeg: ffmpeg -i videoPath -r 30 framesPath/%05d.png"._ And Maybe this command can process video one by one, it's so inconvenient if we process all videos. 
So could you give some suggestions about how to process videos more efficiently？

**Comment by Diananini** [comment]
Write a script to traverse all videos and extract frames for each video

**Comment by erwangccc** [comment]
> 
OK, Thanks

**Comment by erwangccc** [comment]
Hi, i realize that videos size is about 42GB, But the frames from one video are about 2GB.  It's almost 2T after processing all videos, is it normal? If it's normal, I think it's too huge for my device.

**Comment by Diananini** [comment]
PNG is a lossless compression format, thus requiring a lot of storage space. You can try other lossy compression formats, but this will decrease the accuracy of the model.

**Comment by erwangccc** [comment]
@Diananini Thanks for your response.
I saved frames to 'jpg' data which is a compress format. All videos will generate 90GB data. I also think it will decrease the accuracy. Have you trian the model based on differet format data, such as 'jpg' format. How much will the accuray drop? Thanks

**Comment by Diananini** [comment]
We haven't trained the model on JPG images. We would appreciate it if you would like to report the experiment results for reference.

**Comment by erwangccc** [comment]
I'll share the results with you after the training.  May i have you wechat please? The communication efficiency here is too low.  My WeChat: wangshaochang. Thanks
