### ISSUE TITLE
I would like to apply for the dataset.But after I send the email,I get no reply.Is there anything wrong?

### ISSUE THREAD

**Issue by explorer66** [Diananini/LD-ConGR-CVPR2022#7]

**Comment by Diananini** [comment]
Sorry for not replying in time. I have sent you the data download link. You can check your email now.

**Comment by explorer66** [comment]
Thanks very much!I have successfully downloaded the dataset and tried to extract the frames from the videos following your instructions but I found that there are too much frames.I just extracted videos from the first 20 directories and the size of data is already 1.1TB.I wonder how large the whole dataset is after frame extraction?

**Comment by Diananini** [comment]
About 3.8 TB. If you don't have enough space, maybe you can try to save the frames with lower quality and smaller size.

**Comment by explorer66** [comment]
Thanks for your advice.But if I train my model on your dataset,I think the performance of the model will decrease?So the best method is maybe to buy a larger disk?

**Comment by Diananini** [comment]
Yeah, that's true.
